apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "{{ .Values.deploymentLabel }}.{{ .Values.serviceName }}.hackathon.el8.io"
  gateways:
  - {{ include "chart.fullname" . }}-gateway
  http:
  - route:
    - destination:
        host: {{ include "chart.fullname" . }}
        port:
          number: 80

# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: {{ include "chart.fullname" . }}-vs
# spec:
#   hosts:
#   - "*"
#   gateways:
#   - {{ include "chart.fullname" . }}-gateway
#   http:
#   - match:
#     - uri:
#         prefix: /{{ .Values.deploymentLabel }}/{{ .Values.serviceName }}/
#     - uri:
#         prefix: /{{ .Values.deploymentLabel }}/{{ .Values.serviceName }}
#     rewrite:
#         uri: "/"
#     route:
#     - destination:
#         port:
#           number: 80
#         host: {{ include "chart.fullname" . }}